import 'dart:io';
import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:path_provider/path_provider.dart';

/// A utility class for managing disk-based image caching.
///
/// This class generates a unique file path for each image URL
/// using an MD5 hash and stores it in the temporary directory.
///
/// It helps avoid duplicate downloads by reusing cached files.
class DiskCache {
  /// Returns a [File] reference for the given image [url].
  ///
  /// The file path is generated by hashing the URL using MD5,
  /// ensuring a unique and consistent cache key.
  ///
  /// The file is stored in the device's temporary directory.
  ///
  /// Example:
  /// ```dart
  /// final file = await DiskCache().getFile("https://example.com/image.jpg");
  /// ```
  Future<File> getFile(String url) async {
    final dir = await getTemporaryDirectory();

    /// Generate a unique cache key using MD5 hash
    final key = md5.convert(utf8.encode(url)).toString();

    /// Create file path using hashed key
    final file = File("${dir.path}/$key");

    return file;
  }
}
